'use client'

import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, Menu, Moon, Network, Plus, Sun, X } from 'lucide-react'

const queries = [
  { q: 'Help me code an API', a: "I'll help you build a Python API since that's your preference", note: 'Cortex remembered from 3 weeks ago ↗', path: ['User', 'Prefers', 'Python', 'Builds', 'API'] },
  { q: 'How should I structure this app?', a: 'Let’s use the modular architecture you prefer for scalable products', note: 'Cortex remembered from 2 months ago ↗', path: ['User', 'Prefers', 'Modular', 'Builds', 'Apps'] },
]
const faqs = [
  ['How is this different from ChatGPT’s memory?', 'Cortex is a model-agnostic memory layer. It persists structured context across models, tools, and platforms instead of living inside one chat product.'],
  ['What is the Universal AI Protocol?', 'Cortex uses JSON-LD, a W3C standard, to represent memories as semantic triplets that any AI model can understand. Your context in ChatGPT can be read by Claude, Gemini, or any tool that supports the open protocol.'],
  ['Which AIs support the Cortex protocol?', 'Currently: ChatGPT, Claude, and any model via our MCP server or API. Because the protocol is open, any AI platform can add native support.'],
  ['Where is my data stored?', 'You choose. Start locally, use Cortex Cloud, or deploy the open protocol on your own infrastructure for complete control.'],
  ['Can I export my memories?', 'Always. Memories are portable and exportable as structured JSON-LD. You are never locked into the Cortex format.'],
  ['How does the decay algorithm work?', 'Memories gain or lose relevance based on recency, repetition, and explicit importance. You can tune or disable decay for critical context.'],
]

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduce = useReducedMotion()
  return <motion.div className={className} initial={{ opacity: 0, y: reduce ? 0 : 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>
}

function Graph({ active = 4 }: { active?: number }) {
  const points = [[32,90],[100,45],[168,112],[240,46],[305,98],[370,38],[430,104],[492,55]]
  const edges = [[0,1],[1,2],[1,3],[2,3],[2,4],[3,5],[4,5],[4,6],[5,7],[6,7]]
  return <svg className="graph" viewBox="0 0 525 150" role="img" aria-label="Cortex memory graph visualization">
    {edges.map(([a,b], i) => <path key={i} d={`M${points[a][0]} ${points[a][1]} Q ${(points[a][0]+points[b][0])/2} ${(points[a][1]+points[b][1])/2-25} ${points[b][0]} ${points[b][1]}`} className={i < active ? 'graph-path active' : 'graph-path'} style={{ animationDelay: `${i * 110}ms` }} />)}
    {points.map(([x,y], i) => <circle key={i} cx={x} cy={y} r={i < active ? 5 : 3} className={i < active ? 'graph-node active' : 'graph-node'} style={{ animationDelay: `${i * 140}ms` }} />)}
  </svg>
}

function ThemeToggle() {
  const [dark, setDark] = useState(false)
  useEffect(() => { const saved = localStorage.getItem('cortex-theme'); const isDark = saved === 'dark'; setDark(isDark); document.documentElement.classList.toggle('dark', isDark) }, [])
  const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle('dark', next); localStorage.setItem('cortex-theme', next ? 'dark' : 'light') }
  return <button className="icon-button" onClick={toggle} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button>
}

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState(0)
  const [annual, setAnnual] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  return <main>
    <header className="nav"><a href="#top" className="logo">Cortex<span>.</span></a><nav className="nav-links"><a href="#how">How it works</a><a href="#specs">Specs</a><a href="#pricing">Pricing</a><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a></nav><div className="nav-actions"><ThemeToggle /><a href="#pricing" className="button small">Start free <ArrowRight size={15}/></a><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X/> : <Menu/>}</button></div></header>
    <AnimatePresence>{menu && <motion.div className="mobile-menu" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}><a href="#how" onClick={() => setMenu(false)}>How it works</a><a href="#specs" onClick={() => setMenu(false)}>Specs</a><a href="#pricing" onClick={() => setMenu(false)}>Pricing</a><a href="#faq" onClick={() => setMenu(false)}>FAQ</a></motion.div>}</AnimatePresence>
    <section id="top" className="hero wrap"><div className="hero-copy"><p className="eyebrow">MEMORY INFRASTRUCTURE / 01</p><h1>The Memory &amp;<br/><em>Protocol</em> Layer for AI.</h1><p className="hero-sub">Stop repeating yourself. Give every AI model a permanent, cross-platform memory that learns like a human brain—and a universal language to talk to each other.</p><div className="hero-actions"><a className="button" href="#pricing">Start free <ArrowRight size={17}/></a><a className="button ghost" href="#demo">View demo <ArrowRight size={17}/></a></div><p className="micro">Open protocol · Rust core · Built for developers</p></div><div className="hero-visual"><div className="visual-label"><Network size={15}/> LIVE MEMORY GRAPH <span>●</span></div><Graph active={7}/><div className="visual-caption"><span>context_window</span><strong>∞</strong><small>persistent / cross-platform</small></div></div></section>
    <section className="section muted"><div className="wrap"><Reveal><p className="eyebrow">THE PROBLEM / 02</p><h2>AI has <em>amnesia.</em></h2><p className="lead">Every conversation starts from zero. Your context disappears between tabs, tools, and Tuesday.</p></Reveal><div className="pain-grid">{[['01','ChatGPT forgets your preferences','Your workflows shouldn’t need a re-introduction.'],['02','Claude can’t remember last week','Good ideas vanish when the window closes.'],['03','Every chat starts from zero','The cost of repeating yourself compounds.']].map(([n,t,d]) => <Reveal key={n}><article className="pain-card"><span className="card-num">{n}</span><div className="reset-icon"><Network size={21}/></div><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div><div className="stat"><strong>47<span>×</span></strong><p>times users repeat themselves<br/><span>every month</span></p></div></div></section>
    <section className="section protocol-section"><div className="wrap"><Reveal><p className="eyebrow">AI CAN&apos;T TALK TO EACH OTHER / 02.5</p><h2>Every AI speaks<br/><em>a different language.</em></h2><p className="lead">ChatGPT can&apos;t read Claude&apos;s context. Gemini doesn&apos;t understand your local model&apos;s state. Every tool rebuilds the world from scratch.</p></Reveal><div className="pain-grid">{[['01','Incompatible formats','Your conversation in one AI is invisible to another.'],['02','Wasted translation','Developers write custom adapters for every integration.'],['03','No shared understanding','Context dies at the API boundary.']].map(([n,t,d]) => <Reveal key={n}><article className="pain-card"><span className="card-num">{n}</span><div className="reset-icon"><Network size={21}/></div><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div><div className="stat"><strong>83<span>%</span></strong><p>of AI tool overhead is format translation<br/><span>the cost of silos</span></p></div></div></section>
    <section id="how" className="section wrap"><Reveal><p className="eyebrow">THE PROTOCOL / 03</p><h2>From thought<br/>to <em>universal memory.</em></h2></Reveal><div className="timeline">{[['Intercept','Capture context while it is still in motion.'],['Extract','Turn raw conversation into useful, structured signals.'],['Normalize','Convert to language-agnostic semantic triplets (JSON-LD).'],['Store','Connect memories in a permanent, cross-platform mesh.'],['Recall','Surface the right context to any AI model, in their native format.']].map(([t,d], i) => <Reveal key={t}><div className="step"><div className="step-marker">0{i+1}</div><div><p className="mono">{['CAPTURE','STRUCTURE','TRANSLATE','PERSIST','ACTIVATE'][i]}</p><h3>{t}</h3><p>{d}</p></div><div className="step-art"><Graph active={i + 2}/></div></div></Reveal>)}</div></section>
    <section id="demo" className="section demo-section"><div className="wrap"><Reveal><p className="eyebrow">SEE IT IN ACTION / 04</p><h2>Memory that <em>shows up.</em></h2><div className="demo-toggle" role="group" aria-label="Demo mode"><span>Show:</span><button className="selected">Memory Recall</button><button>Cross-AI Translation</button></div></Reveal><div className="demo-grid"><div className="chat-box"><div className="box-top"><span><i/> cortex.session</span><span className="mono">LIVE</span></div><div className="chat-body"><p className="chat-label">YOU</p><div className="bubble user">{queries[query].q}</div><p className="chat-label">CORTEX AI</p><div className="bubble ai">{queries[query].a}</div><p className="annotation">↗ {queries[query].note}</p></div><button className="try-button" onClick={() => setQuery((query + 1) % queries.length)}>Try a different query <ArrowRight size={15}/></button></div><div className="demo-graph"><div className="box-top"><span>MEMORY NETWORK</span><span className="status">● ACTIVE</span></div><Graph active={query ? 8 : 6}/><div className="path-tags">{queries[query].path.map((p, i) => <span key={p} className="path-tag">{p}{i < 4 && <ArrowRight size={12}/>}</span>)}</div><p className="mono graph-foot">latency: 14ms · confidence: 0.98</p></div></div></div></section>
    <section id="specs" className="section wrap"><Reveal><p className="eyebrow">UNDER THE HOOD / 05</p><h2>Built for <em>scale.</em></h2></Reveal><div className="spec-grid">{[['PERFORMANCE','Sub-20ms','Query latency at the edge.'],['EFFICIENCY','70–90%','Less context token spend.'],['CAPACITY','∞','Memory without a ceiling.'],['CORE','Rust','Fast, safe, and portable.'],['STORAGE','Graph DB','Relationships are first-class.'],['PROTOCOL','JSON-LD','Open by design.']].map(([label,value,desc]) => <div className="spec" key={label}><p className="mono">{label}</p><strong>{value}</strong><p>{desc}</p><div className="spec-line"/></div>)}</div></section>
    <section className="section muted proof"><div className="wrap"><Reveal><p className="eyebrow">EARLY SIGNAL / 06</p><h2>Designed to be <em>shared.</em></h2></Reveal><div className="metrics"><div><strong>2.4k</strong><span>GitHub stars</span></div><div><strong>840</strong><span>Discord members</span></div><div><strong>14ms</strong><span>median query</span></div></div><p className="trust">Trusted by builders at <span>GitHub</span><span>Vercel</span><span>Anthropic</span><span>OpenAI</span></p></div></section>
    <section id="pricing" className="section wrap"><div className="pricing-head"><Reveal><p className="eyebrow">ACCESS / 07</p><h2>Start with <em>memory.</em></h2></Reveal><div className="billing"><button className={!annual ? 'selected' : ''} onClick={() => setAnnual(false)}>Monthly</button><button className={annual ? 'selected' : ''} onClick={() => setAnnual(true)}>Annual <span>Save 20%</span></button></div></div><div className="pricing-grid">{[['Free','$0','For individuals',['5k nodes','Local storage','Community support']],['Pro',annual ? '$86/yr' : '$9/mo','For power users',['Unlimited nodes','Cloud sync','Priority support']],['Enterprise','Custom','For AI platforms',['On-premise','SLA','Dedicated support']]].map(([name,price,desc,features], i) => <article className={`price-card ${i === 1 ? 'featured' : ''}`} key={name}>{i === 1 && <span className="popular">MOST POPULAR</span>}<p className="mono">{name.toUpperCase()}</p><h3>{price}</h3><p>{desc}</p><ul>{(features as string[]).map(f => <li key={f}><Check size={16}/>{f}</li>)}</ul><a href="#top" className={`button ${i === 1 ? '' : 'ghost'}`}>{i === 2 ? 'Contact sales' : i === 1 ? 'Start trial' : 'Get started'} <ArrowRight size={16}/></a></article>)}</div></section>
    <section id="faq" className="section faq wrap"><Reveal><p className="eyebrow">COMMON QUESTIONS / 08</p><h2>Still curious?</h2></Reveal><div className="faq-list">{faqs.map(([q,a], i) => <div className="faq-item" key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i}><span>{q}</span>{openFaq === i ? <X size={19}/> : <Plus size={19}/>}</button><AnimatePresence initial={false}>{openFaq === i && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section>
    <section className="cta"><div><p className="eyebrow">YOUR NEXT SESSION</p><h2>Stop forgetting.<br/>Start remembering.</h2><p>Join 10,000+ developers giving AI permanent memory.</p><a href="#pricing" className="button light">Start free today <ArrowRight size={17}/></a></div></section>
    <footer className="footer wrap"><div className="footer-watermark" aria-hidden="true"><span>CORTEX</span><b>.</b></div><div className="footer-top"><a className="logo" href="#top">Cortex<span>.</span></a><div className="footer-links"><div><p>PRODUCT</p><a href="#how">Docs</a><a href="#pricing">Pricing</a><a href="#top">Changelog</a></div><div><p>COMPANY</p><a href="#top">About</a><a href="#top">Blog</a><a href="#top">Contact</a></div><div><p>COMMUNITY</p><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a><a href="#top">Discord</a><a href="#top">Email</a></div></div></div><div className="footer-bottom"><span>© 2026 Cortex</span><span className="mono">MEMORY, PERMANENTLY.</span><ThemeToggle /></div></footer>
  </main>
}
