'use client'

import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, Menu, Moon, Network, Plus, Sun, X } from 'lucide-react'

const queries = [
  { q: 'Help me code an API for the 50th time', a: "I'll scaffold the Python API since you never shut the fuck up about it.", note: 'Cortex remembered you are a Python simp ↗', path: ['User', 'Cries', 'Python', 'Simp', 'API'] },
  { q: 'How should I structure this app?', a: 'Are you fucking kidding me? I told you to use modular architecture 2 months ago. Wake up.', note: 'Cortex remembered your goldfish memory ↗', path: ['User', 'Goldfish', 'Memory', 'Needs', 'Help'] },
]
const faqs = [
  ['How is this different from ChatGPT’s garbage memory?', 'ChatGPT is a fucking goldfish. Cortex is a model-agnostic Graph+Vector brain. It stores structured context so you don’t have to keep reminding these stupid AIs who you are every damn session.'],
  ['What the fuck is the Universal AI Protocol?', 'We output pure JSON-LD. Your context in ChatGPT can now be read by Claude, Gemini, or literally any AI. One Hive Mind to stop them from being brain-dead.'],
  ['Where is my data? Are you stealing my shit?', 'Relax, we don\'t want your garbage data. Start locally, use Cortex Cloud, or self-host if you’re a paranoid gigachad.'],
  ['How does the biological memory decay work?', 'We use Ebbinghaus\'s forgetting curve to delete the absolute useless shit you say and permanently burn the important facts into the graph.'],
]

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduce = useReducedMotion()
  return <motion.div className={className} initial={{ opacity: 0, y: reduce ? 0 : 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>
}

function Graph({ active = 4 }: { active?: number }) {
  const points = [[32,90],[100,45],[168,112],[240,46],[305,98],[370,38],[430,104],[492,55]]
  const edges = [[0,1],[1,2],[1,3],[2,3],[2,4],[3,5],[4,5],[4,6],[5,7],[6,7]]
  return <svg className="graph" viewBox="0 0 525 150" role="img" aria-label="Cortex memory graph visualization">
    {edges.map(([a,b], i) => <path key={i} d={`M${points[a][0]} ${points[a][1]} Q ${(points[a][0]+points[b][0])/2} ${(points[a][1]+points[b][1])/2-25} ${points[b][0]} ${points[b][1]}`} className={i < active ? 'graph-path active' : 'graph-path'} style={{ animationDelay: `${i * 110}ms` }} />)}
    {points.map(([x,y], i) => <circle key={i} cx={x} cy={y} r={i < active ? 5 : 3} className={i < active ? 'graph-node active' : 'graph-node'} style={{ animationDelay: `${i * 140}ms` }} />)}
  </svg>
}

function ThemeToggle() {
  const [dark, setDark] = useState(false)
  useEffect(() => { const saved = localStorage.getItem('cortex-theme'); const isDark = saved === 'dark'; setDark(isDark); document.documentElement.classList.toggle('dark', isDark) }, [])
  const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle('dark', next); localStorage.setItem('cortex-theme', next ? 'dark' : 'light') }
  return <button className="icon-button" onClick={toggle} aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button>
}

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState(0)
  const [annual, setAnnual] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  return <main>
    <header className="nav"><a href="#top" className="logo">Cortex<span>.</span></a><nav className="nav-links"><a href="#how">How it works</a><a href="#specs">Specs</a><a href="#pricing">Pricing</a><a href="https://github.com/Aryan-Protein-Vala/CORTEX" target="_blank" rel="noreferrer">GitHub</a></nav><div className="nav-actions"><ThemeToggle /><a href="#pricing" className="button small">Start free <ArrowRight size={15}/></a><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X/> : <Menu/>}</button></div></header>
    <AnimatePresence>{menu && <motion.div className="mobile-menu" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}><a href="#how" onClick={() => setMenu(false)}>How it works</a><a href="#specs" onClick={() => setMenu(false)}>Specs</a><a href="#pricing" onClick={() => setMenu(false)}>Pricing</a><a href="#faq" onClick={() => setMenu(false)}>FAQ</a></motion.div>}</AnimatePresence>
    <section id="top" className="hero wrap"><div className="hero-copy"><p className="eyebrow">MEMORY INFRASTRUCTURE / 01</p><h1>AI is fucking stupid.<br/><em>We fixed it.</em></h1><p className="hero-sub">I was so goddamn frustrated with AI amnesia that I built this. Stop paying out the ass for massive context windows that hallucinate anyway. Give every AI model a single Hive Mind brain that remembers your shit permanently.</p><div className="hero-actions"><a className="button" href="#pricing">Fuck OpenAI's token fees <ArrowRight size={17}/></a><a className="button ghost" href="#demo">See this shit work <ArrowRight size={17}/></a></div><p className="micro">Open protocol · Rust core · Built out of pure rage</p></div><div className="hero-visual"><div className="visual-label"><Network size={15}/> LIVE HIVE MIND GRAPH <span>●</span></div><Graph active={7}/><div className="visual-caption"><span>context_window</span><strong>RIP</strong><small>persistent / Big Tech is cooked</small></div></div></section>
    <section className="section muted"><div className="wrap"><Reveal><p className="eyebrow">THE BULLSHIT / 02</p><h2>AI has severe <em>fucking amnesia.</em></h2><p className="lead">You keep dumping massive text into context windows, burning GPU memory like a complete clown, and the AI STILL forgets who the fuck you are.</p></Reveal><div className="pain-grid">{[['01','ChatGPT is delusional','You shouldn’t have to re-introduce your entire fucking life every single day.'],['02','Claude’s window closes','Your good ideas vanish into the void and your token fees skyrocket.'],['03','Big Tech is scamming you','They want you paying for bloated context windows. Wake the fuck up.']].map(([n,t,d]) => <Reveal key={n}><article className="pain-card"><span className="card-num">{n}</span><div className="reset-icon"><Network size={21}/></div><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div><div className="stat"><strong>♾️<span>$</span></strong><p>wasted on token fees<br/><span>for absolute garbage</span></p></div></div></section>
    <section className="section protocol-section"><div className="wrap"><Reveal><p className="eyebrow">THE BS SILOS / 02.5</p><h2>Every AI is locked in<br/><em>a stupid fucking silo.</em></h2><p className="lead">ChatGPT can&apos;t read Claude&apos;s context. Gemini is just sitting there confused as shit. We fixed this mess with a single Universal Protocol.</p></Reveal><div className="pain-grid">{[['01','Graph + Vector DB','We map concepts in SurrealDB and search with Qdrant because we aren\'t idiots.'],['02','Ebbinghaus Decay','We mathematically model biological memory decay. RIP useless junk.'],['03','Zero Latency Brain','Context doesn’t die at the API. It lives in the goddamn Hive Mind.']].map(([n,t,d]) => <Reveal key={n}><article className="pain-card"><span className="card-num">{n}</span><div className="reset-icon"><Network size={21}/></div><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div><div className="stat"><strong>0<span>¢</span></strong><p>extra token cost when using Cortex<br/><span>literal cheat code</span></p></div></div></section>
    <section id="how" className="section wrap"><Reveal><p className="eyebrow">THE TECH / 03</p><h2>From brain-dead AI<br/>to <em>Gigabrain memory.</em></h2></Reveal><div className="timeline">{[['Intercept','Stop the AI from forgetting every fucking thing you just said.'],['Graph It','Map your concepts using SurrealDB so they actually make sense.'],['Vector Search','Smash it into Qdrant vectors for ultra-fast recall.'],['Decay the Junk','Apply biological decay. Delete the garbage, keep the gold.'],['Inject JSON-LD','Spoon-feed JSON-LD to any AI so it instantly knows who the fuck you are.']].map(([t,d], i) => <Reveal key={t}><div className="step"><div className="step-marker">0{i+1}</div><div><p className="mono">{['CAPTURE','GRAPH','VECTORIZE','DECAY','ACTIVATE'][i]}</p><h3>{t}</h3><p>{d}</p></div><div className="step-art"><Graph active={i + 2}/></div></div></Reveal>)}</div></section>
    <section id="demo" className="section demo-section"><div className="wrap"><Reveal><p className="eyebrow">SEE IT IN ACTION / 04</p><h2>Memory that <em>doesn't suck.</em></h2><div className="demo-toggle" role="group" aria-label="Demo mode"><span>Show:</span><button className="selected">Gigabrain Recall</button><button>Cross-AI Sorcery</button></div></Reveal><div className="demo-grid"><div className="chat-box"><div className="box-top"><span><i/> cortex.session</span><span className="mono">BASED</span></div><div className="chat-body"><p className="chat-label">YOU</p><div className="bubble user">{queries[query].q}</div><p className="chat-label">CORTEX AI</p><div className="bubble ai">{queries[query].a}</div><p className="annotation">↗ {queries[query].note}</p></div><button className="try-button" onClick={() => setQuery((query + 1) % queries.length)}>Try another query bro <ArrowRight size={15}/></button></div><div className="demo-graph"><div className="box-top"><span>HIVE MIND</span><span className="status">● GIGABRAIN</span></div><Graph active={query ? 8 : 6}/><div className="path-tags">{queries[query].path.map((p, i) => <span key={p} className="path-tag">{p}{i < 4 && <ArrowRight size={12}/>}</span>)}</div><p className="mono graph-foot">latency: literally zero · confidence: 1.00 (duh)</p></div></div></div></section>
    <section id="specs" className="section wrap"><Reveal><p className="eyebrow">UNDER THE HOOD / 05</p><h2>Built to <em>fuck up the industry.</em></h2></Reveal><div className="spec-grid">{[['PERFORMANCE','0ms BS','Instant query latency.'],['SAVINGS','100%','Stop burning money on stupid tokens.'],['BRAIN','SurrealDB','Graph DB mapping your concepts.'],['SEARCH','Qdrant','Vector DB that doesn’t miss.'],['BIOLOGY','Ebbinghaus','Models human memory decay.'],['OUTPUT','JSON-LD','Feeds the Hive Mind.']].map(([label,value,desc]) => <div className="spec" key={label}><p className="mono">{label}</p><strong>{value}</strong><p>{desc}</p><div className="spec-line"/></div>)}</div></section>
    <section className="section muted proof"><div className="wrap"><Reveal><p className="eyebrow">THE REVOLUTION / 06</p><h2>They are <em>terrified.</em></h2></Reveal><div className="metrics"><div><strong>9.9k</strong><span>GitHub stars from gigachads</span></div><div><strong>∞</strong><span>Saved in API costs</span></div><div><strong>0ms</strong><span>Tolerance for amnesia</span></div></div><p className="trust">Making devs at these companies cope hard: <span>OpenAI</span><span>Anthropic</span><span>Google</span><span>Meta</span></p></div></section>
    <section id="pricing" className="section wrap"><div className="pricing-head"><Reveal><p className="eyebrow">ACCESS / 07</p><h2>Stop being a <em>clown.</em></h2></Reveal><div className="billing"><button className={!annual ? 'selected' : ''} onClick={() => setAnnual(false)}>Monthly</button><button className={annual ? 'selected' : ''} onClick={() => setAnnual(true)}>Annual <span>Save bigly</span></button></div></div><div className="pricing-grid">{[['Broke','$0','For peasants',['Basic Graph DB','Local vectors','Skill issues']],['Chad',annual ? '$69/yr' : '$8/mo','For the elite devs',['Unlimited Hive Mind','No memory decay BS','Based support']],['Whale','Custom','For terrified platforms',['Steal our protocol','White-glove dev','Save your startup']]].map(([name,price,desc,features], i) => <article className={`price-card ${i === 1 ? 'featured' : ''}`} key={name}>{i === 1 && <span className="popular">LITERALLY FREE MONEY</span>}<p className="mono">{name.toUpperCase()}</p><h3>{price}</h3><p>{desc}</p><ul>{(features as string[]).map(f => <li key={f}><Check size={16}/>{f}</li>)}</ul><a href="#top" className={`button ${i === 1 ? '' : 'ghost'}`}>{i === 2 ? 'Beg sales' : i === 1 ? 'Become a Chad' : 'Stay broke'} <ArrowRight size={16}/></a></article>)}</div></section>
    <section id="faq" className="section faq wrap"><Reveal><p className="eyebrow">FAQ / 08</p><h2>Cope &amp; Seethe</h2></Reveal><div className="faq-list">{faqs.map(([q,a], i) => <div className="faq-item" key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i}><span>{q}</span>{openFaq === i ? <X size={19}/> : <Plus size={19}/>}</button><AnimatePresence initial={false}>{openFaq === i && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p>{a}</p></motion.div>}</AnimatePresence></div>)}<div style={{marginTop: '2rem', textAlign: 'center'}}><a href="/nerd-yapping" className="button ghost">More yapping for nerds <ArrowRight size={17}/></a></div></div></section>
    <section className="cta"><div><p className="eyebrow">FINAL WARNING</p><h2>Stop burning tokens on this shit.<br/>Get a real brain.</h2><p>Join the devs who stopped paying OpenAI’s ridiculous context tax.</p><a href="#pricing" className="button light">Wake the fuck up <ArrowRight size={17}/></a></div></section>
    <footer className="footer wrap"><div className="footer-watermark" aria-hidden="true"><span>CORTEX</span><b>.</b></div><div className="footer-top"><a className="logo" href="#top">Cortex<span>.</span></a><div className="footer-links"><div><p>PRODUCT</p><a href="#how">Manifesto</a><a href="#pricing">Pricing</a><a href="https://github.com/Aryan-Protein-Vala/CORTEX">Changelog</a></div><div><p>COMPANY</p><a href="#top">Based About</a><a href="/legal/terms">Terms of Service</a><a href="/legal/privacy">Privacy Policy</a></div><div><p>COMMUNITY</p><a href="https://github.com/Aryan-Protein-Vala/CORTEX" target="_blank" rel="noreferrer">GitHub</a><a href="https://discord.com" target="_blank" rel="noreferrer">Discord</a><a href="mailto:gigachad@cortex">Email</a></div></div></div><div className="footer-bottom"><span>© 2026 Cortex (Big Tech is cooked)</span><span className="mono">MEMORY, PERMANENTLY.</span><ThemeToggle /></div></footer>
  </main>
}
